server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/yaoyyy/microservice-config-repo.git
          username: yaoyyy
          password: anxiaoluo1221