server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@peer-auth:8760/eureka,http://peer2:8762/eureka
spring:
  application:
    name: zuul
zuul:
  sensitive-headers: yaoyy
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000