# 三台eureka都叫abc
spring:
  application:
    name: abc

---
# eureka-auth
server:
  port: 8760
eureka:
  client:
    service-url:
      # eureka所在的服务器地址，这里配多个就是集群了，包括自己！
      # defaultZone: http://peer-auth:8760/eureka, http://peer1:8761/eureka, http://peer2:8762/eureka
      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka
  instance:
    hostname: peer-auth
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin
spring:
  profiles: auth

---
# eureka1号机子
eureka:
  client:
    service-url:
      # eureka所在的服务器地址，这里配多个就是集群了，包括自己！
      # defaultZone: http://peer1:8761/eureka, http://peer-auth:8760/eureka, http://peer2:8762/eureka
      defaultZone: http://peer2:8762/eureka,http://admin:admin@peer-auth:8760/eureka
  instance:
    hostname: peer1
security:
  basic:
    enabled: false
server:
  port: 8761
spring:
  profiles: eureka1

---
# eureka2号机子
eureka:
  client:
    service-url:
      # eureka所在的服务器地址，这里配多个就是集群了，包括自己！
      # defaultZone: http://peer1:8761/eureka, http://peer-auth:8760/eureka, http://peer2:8762/eureka
      defaultZone: http://peer1:8761/eureka,http://admin:admin@peer-auth:8760/eureka
  instance:
    hostname: peer2
security:
  basic:
    enabled: false
server:
  port: 8762
spring:
  profiles: eureka2